### ISSUE TITLE
структура проекта

### ISSUE THREAD

**Issue by Maxwe11** [KeyGen/Easy-work#1]
1) тебе самому удобно пользоватся такой структурой проекта? под структурой я имею ввиду расположение файлов в папках
2)  Easy-work/Major_components/Keyboard/keyboard/keyboard.cpp
почему коды клавиш вписаны в код? почему не используешь Qt-шный enum т.е. например вместо
if(event->key() == 16777219 /_Backspace_/)
писать
if(event->key() == Qt::Key_Backspace)

**Comment by KeyGen** [comment]
Я это исправил. Но почему-то Qt::Key_Enter не работает написал кодом...
